---
COMMON_PKG_LIST:
  - { name: git }
  - { name: wget }
HOSTNAME: '1mg.biz'
PATH_1MG: /usr/local/1mg
COMMON_MKDIRS:
  - {
    path: "{{PATH_1MG}}",
    owner: 'root',
    group: 'root',
    mode: '0775',
    recurse: 'no'
  }
  - {
    path: "{{PATH_1MG}}/etc",
    owner: 'root',
    group: 'root',
    mode: '0775',
    recurse: 'no'
  }
  - {
    path: "{{PATH_1MG}}/data",
    owner: 'root',
    group: 'root',
    mode: '0755',
    recurse: 'no'
  }
  # - {
  #   path: "{{PATH_1MG}}/www",
  #   owner: 'nginx',
  #   group: 'nginx',
  #   mode: '0775',
  #   recurse: 'no'
  # }
  - {
    path: "{{PATH_1MG}}/logs",
    owner: 'root',
    group: 'root',
    mode: '0755',
    recurse: 'no'
  }
  - {
    path: "{{PATH_1MG}}/home",
    owner: 'root',
    group: 'root',
    mode: '0755',
    recurse: 'no'
  }
  - {
    path: "{{PATH_1MG}}/bin",
    owner: 'root',
    group: 'root',
    mode: '0755',
    recurse: 'no'
  }
