---
- name: Sysctl Setup
  sysctl:
    name: "{{ item.KEY }}"
    value: "{{ item.VALUE }}"
    state: present
    reload: yes
  with_items:
    - "{{ COMMON_SYSCTL_SETTINGS | default([]) }}"
    - "{{ COMMON_HOSTGROUP_SYSCTL_SETTINGS | default([]) }}"
    - "{{ INVENTORY_SYSCTL_SETTINGS | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_SYSCTL_SETTINGS | default([]) }}"
