---
- name: Setup Config
  template:
    src: 'systemd.conf.j2'
    dest: '/etc/systemd.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: "{{ NAME_SERVICE_MANAGER }} restarted {{ NAME_DAEMON }}"
