---
- name: Read specific vars for each of OS and Verion
  include_vars: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"

- include: install_{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml

- include: setup.yml

- name: Daemon Started
  include_role:
    name: common_tasks
    tasks_from: service_started_{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml
  when: not ansible_check_mode
