---
- name: Setup sysctl.conf
  template:
    src: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.sysctl.conf.j2"
    dest: /etc/sysctl.conf
    mode: 0644
    owner: 0
    group: 0
  notify: Reload Sysctl

- name: Setup cron.d/sysstat
  template:
    src: "{{ ansible_os_family }}.sysstat.j2"
    dest: /etc/cron.d/sysstat
    mode: 0644
    owner: 0
    group: 0

- name: Disabled SELinux
  include: setup_selinux.yml
  tags:
    - docker
    - skip-check
