---
- name: Set Config
  template:
    src: sshd_config_{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: "{{ NAME_SERVICE}} restarted {{ daemon_name }}"
