ARRAY_GROUP:
  - {
    name: 'sftponly',
    gid: 1001
    }

ARRAY_USER:
  - {
    name: 'test',
    shell: '/bin/zsh',
    group: 'sftponly',
    home: '/home/test',
    uid: '1000',
    create_home: 'no',
    update_password: 'always',
    }

MACKEREL: {
  APIKEY: "test"
}
