---
- name: Service start {{ daemon_name }}
  service:
    name: "{{ daemon_name }}"
    state: started
    enabled: yes
  listen: Service start {{ daemon_name }}

- name: Service restart {{ daemon_name }}
  service:
    name: "{{ daemon_name }}"
    state: restarted
  listen: Service restart {{ daemon_name }}

- name: Service reloaded {{ daemon_name }}
  service:
    name: "{{ daemon_name }}"
    state: reloaded
  listen: Service reloaded {{ daemon_name }}

- name: Service stop {{ daemon_name }}
  service:
    name: "{{ daemon_name }}"
    state: stopped
    enabled: no
  listen: Service stop {{ daemon_name }}

- name: Systemd start {{ daemon_name }}
  systemd:
    name: "{{ daemon_name }}"
    state: started
    enabled: yes
  listen: Systemd start {{ daemon_name }}

- name: Systemd restart {{ daemon_name }}
  systemd:
    name: "{{ daemon_name }}"
    state: restarted
  listen: Systemd restart {{ daemon_name }}

- name: Systemd reloaded {{ daemon_name }}
  systemd:
    name: "{{ daemon_name }}"
    state: reloaded
  listen: Systemd reloaded {{ daemon_name }}

- name: Systemd stop {{ daemon_name }}
  systemd:
    name: "{{ daemon_name }}"
    state: stopped
    enabled: no
  listen: Systemd stop {{ daemon_name }}
