---
- name: Check State "{{ NAME_DAEMON }}"
  shell: "service {{ NAME_DAEMON }} status"
  register: service_status
  changed_when: False
  failed_when: False
  ignore_errors: True
  when: not ansible_check_mode

- name: Stopped "{{ NAME_DAEMON }}"
  shell: echo "Stopped {{ NAME_DAEMON }}"
  notify: "{{ NAME_SERVICE_MANAGER }} stopped {{ NAME_DAEMON }}"
  when:
    - not ansible_check_mode
    - service_status.rc != 3
