---
- name: Check Install Package
  command: rpm -qi {{ item.NAME_PACKAGE }}
  register: installed_status
  changed_when: False
  failed_when: False

- name: Disabled and Stopped ({{ item.NAME_SERVICE }})
  service:
    name: "{{ item.NAME_SERVICE }}"
    enabled: no
    state: stopped
  when:
    - not ansible_check_mode
    - installed_status.rc == 0
